import{notFound}from"next/navigation";import{caseStudies,caseDeliverables,getCase}from"../data";
export function generateStaticParams(){return caseStudies.map(x=>({slug:x.slug}))}
export default async function CasePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const item=getCase(slug);if(!item)notFound();const details=caseDeliverables[slug];const next=caseStudies[(caseStudies.findIndex(x=>x.slug===slug)+1)%caseStudies.length];return <main className={`casePage ${item.tone}`}>
<header className="caseHeader shell"><a className="logo" href="/">Supernova<i>✦</i></a><a href="/#projects">← Все проекты</a><a href="/#contact">Обсудить проект ↗</a></header>
<section className="caseHero shell"><div className="caseMeta"><span>{item.number} / {item.year}</span><span>{item.category}</span></div><h1>{item.title}</h1><p>{item.headline}</p><div className="caseOrb"><i/><b>{item.number}</b></div></section>
<section className="caseIntro shell"><p className="caseKicker">О проекте</p><h2>{item.intro}</h2></section>
<section className="caseStory shell"><article><span>01 / Задача</span><p>{item.challenge}</p></article><article><span>02 / Решение</span><p>{item.solution}</p></article></section>
<section className="caseScope shell"><div><p className="caseKicker">Что сделали</p><h2>Полный цикл<br/><em>запуска бренда</em></h2></div><ol>{item.works.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></section>
<section className="deliverables shell"><div className="deliverablesHead"><p className="caseKicker">Материалы проекта</p><h2>Показываем,<br/><em>что внутри</em></h2><p>Каждый пункт раскрыт как самостоятельный результат работы команды.</p></div>{details.map((d,i)=><article className="deliverable" key={d.title}><div className="deliverableCopy"><span>0{i+1} / {d.tag}</span><h3>{d.title}</h3><p>{d.summary}</p><ul>{d.bullets.map(x=><li key={x}>{x}</li>)}</ul></div><div className={`deliverableMock mock${i%3}`}><small>{d.tag}</small><strong>{d.sample}</strong><i>Supernova® / {item.title}</i></div></article>)}</section>
<section className="caseVisual shell"><div className="visualPlanet"><i/><span>Supernova / case {item.number}</span></div><blockquote>«{item.quote}»</blockquote></section>
<section className="caseResults shell"><p className="caseKicker">Результат</p><div>{item.results.map(x=><article key={x.value}><strong>{x.value}</strong><span>{x.label}</span></article>)}</div><small>* Показатели и материалы приведены для демонстрации структуры презентационного кейса.</small></section>
<a className="nextCase" href={`/cases/${next.slug}`}><span>Следующий проект</span><strong>{next.title}</strong><b>↗</b></a></main>}
